import { StyleSheet } from "react-native";
import { ThemeColors } from "../../../shared/theme";

export const getStyles = (theme: ThemeColors) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.background,
  },
  header: {
    backgroundColor: theme.primary,
    paddingTop: 50,
    paddingBottom: 15,
    paddingHorizontal: 20,
    alignItems: 'center',
  },
  headerTitle: {
    color: '#fff',
    fontSize: 20,
    fontWeight: 'bold',
  },
  content: {
    flex: 1,
  },
  contentContainer: {
    flexGrow: 1,
    justifyContent: 'space-between',
    paddingVertical: 30,
  },
  emptyState: {
    backgroundColor: theme.tabBackground,
    marginHorizontal: 30,
    marginTop: 20,
    padding: 40,
    borderRadius: 8,
    alignItems: 'center',
  },
  emptyStateText: {
    color: theme.text,
    fontSize: 16,
    textAlign: 'center',
    lineHeight: 24,
  },
  addButton: {
    backgroundColor: theme.primary,
    marginHorizontal: 50,
    marginBottom: 30,
    paddingVertical: 15,
    borderRadius: 25,
    alignItems: 'center',
  },
  addButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  formContainer: {
    backgroundColor: theme.tabBackground,
    marginHorizontal: 20,
    marginTop: 20,
    padding: 25,
    borderRadius: 15,
  },
  formTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: theme.text,
    marginBottom: 20,
    textAlign: 'center',
  },
  clienteSelectedBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.primaryLight,
    padding: 12,
    borderRadius: 8,
    marginBottom: 15,
    gap: 8,
  },
  clienteSelectedText: {
    fontSize: 15,
    color: theme.primary,
    fontWeight: '600',
  },
  exerciciosListContainer: {
    marginBottom: 15,
    backgroundColor: theme.primaryLight,
    borderRadius: 10,
    padding: 15,
  },
  exerciciosListTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: theme.success,
    marginBottom: 10,
  },
  exercicioAddedCard: {
    backgroundColor: theme.card,
    borderRadius: 8,
    padding: 12,
    marginBottom: 8,
    borderLeftWidth: 4,
    borderLeftColor: theme.success,
  },
  exercicioAddedContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  exercicioAddedInfo: {
    flex: 1,
  },
  exercicioAddedNome: {
    fontSize: 15,
    fontWeight: '600',
    color: theme.text,
    marginBottom: 4,
  },
  exercicioAddedDetalhes: {
    fontSize: 13,
    color: theme.textSecondary,
    marginBottom: 6,
  },
  diaBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.primaryLight,
    alignSelf: 'flex-start',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    gap: 4,
  },
  diaBadgeText: {
    fontSize: 11,
    color: theme.primary,
    fontWeight: '600',
  },
  exercicioActions: {
    flexDirection: 'row',
    gap: 8,
  },
  editExercicioButton: {
    backgroundColor: theme.primaryLight,
    padding: 8,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  deleteExercicioButton: {
    backgroundColor: theme.primaryLight,
    padding: 8,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  buttonsRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 15,
  },
  addExercicioButton: {
    flex: 1,
    backgroundColor: theme.primary,
    borderRadius: 10,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  addExercicioButtonText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '600',
  },
  inputGroup: {
    marginBottom: 15,
  },
  inputLabel: {
    fontSize: 14,
    color: theme.primary,
    marginBottom: 5,
    fontWeight: '500',
  },
  input: {
    backgroundColor: theme.inputBackground,
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 15,
    fontSize: 16,
    color: theme.text,
    borderWidth: 1,
    borderColor: theme.inputBorder,
  },
  concludeButton: {
    backgroundColor: theme.success,
    borderRadius: 25,
    paddingVertical: 15,
    marginTop: 20,
    alignItems: 'center',
  },
  concludeButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  clientsListContainer: {
    marginHorizontal: 20,
    marginTop: 20,
  },
  clientCard: {
    backgroundColor: theme.card,
    borderRadius: 15,
    padding: 20,
    marginBottom: 15,
    shadowColor: theme.shadow,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 3,
  },
  clientHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 15,
    gap: 12,
  },
  clientInfoBlock: {
    flex: 1,
  },
  clientLabel: {
    fontSize: 14,
    color: theme.textSecondary,
    marginBottom: 5,
  },
  clientValue: {
    fontSize: 16,
    color: theme.text,
    fontWeight: '600',
  },
  statusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 12,
  },
  statusBadgeText: {
    color: '#fff',
    fontSize: 13,
    fontWeight: '700',
  },
  statusNeutral: {
    backgroundColor: theme.inputBorder,
  },
  statusPending: {
    backgroundColor: '#FFC107',
  },
  statusAccepted: {
    backgroundColor: theme.success,
  },
  treinoClientCard: {
    backgroundColor: theme.card,
    borderRadius: 15,
    padding: 20,
    marginBottom: 15,
    shadowColor: theme.shadow,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 3,
  },
  treinoClientInfo: {
    width: '100%',
  },
  clientInfoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 15,
  },
  treinoClientLabel: {
    fontSize: 14,
    color: theme.textSecondary,
    marginBottom: 5,
  },
  treinoClientValue: {
    fontSize: 16,
    color: theme.text,
    fontWeight: '600',
  },
  montarTreinoButton: {
    backgroundColor: theme.primary,
    borderRadius: 10,
    paddingVertical: 12,
    paddingHorizontal: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  montarTreinoButtonText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '600',
  },
  infoButton: {
    backgroundColor: theme.primaryLight,
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  infoButtonText: {
    color: theme.primary,
    fontSize: 14,
    fontWeight: '700',
  },
  treinoInputRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 10,
  },
  treinoInputSmall: {
    flex: 1,
  },
  treinosListContainer: {
    marginHorizontal: 20,
    marginTop: 20,
  },
  treinoCard: {
    backgroundColor: theme.card,
    borderRadius: 10,
    padding: 20,
    marginBottom: 15,
    shadowColor: theme.shadow,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 3,
  },
  treinoCardTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: theme.primary,
    flex: 1,
  },
  treinoCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  treinoCardActions: {
    flexDirection: 'row',
    gap: 8,
  },
  editTreinoCardButton: {
    backgroundColor: theme.primaryLight,
    padding: 8,
    borderRadius: 8,
  },
  deleteTreinoCardButton: {
    backgroundColor: theme.primaryLight,
    padding: 8,
    borderRadius: 8,
  },
  exercicioCount: {
    fontSize: 13,
    color: theme.textSecondary,
    marginBottom: 12,
  },
  exercicioItem: {
    backgroundColor: theme.backgroundSecondary,
    padding: 12,
    borderRadius: 8,
    marginBottom: 8,
  },
  exercicioItemContent: {
    gap: 4,
  },
  exercicioText: {
    fontSize: 15,
    color: theme.text,
    fontWeight: '600',
  },
  exercicioDetails: {
    fontSize: 13,
    color: theme.textSecondary,
  },
  bottomNav: {
    flexDirection: 'row',
    backgroundColor: theme.primary,
    paddingTop: 15,
    paddingBottom: 45,
    borderTopWidth: 1,
    borderTopColor: theme.primaryDark,
  },
  navButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  navButtonActive: {
    backgroundColor: 'transparent',
  },
  navButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '500',
  },
  navButtonTextActive: {
    color: '#fff',
    fontWeight: '600',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContainer: {
    width: '90%',
    maxHeight: '85%',
    backgroundColor: theme.card,
    borderRadius: 20,
    overflow: 'hidden',
    shadowColor: theme.shadow,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 10,
  },
  modalScroll: {
    padding: 20,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  modalTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: theme.primary,
  },
  closeButton: {
    padding: 5,
  },
  modalButtonsContainer: {
    marginTop: 25,
    marginBottom: 15,
  },
  treinoActionsContainer: {
    flexDirection: 'row',
    gap: 10,
  },
  editarTreinoButton: {
    flex: 1,
    backgroundColor: theme.warning,
    borderRadius: 10,
    paddingVertical: 12,
    paddingHorizontal: 15,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  editarTreinoButtonText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '600',
  },
  mostrarTreinoButton: {
    flex: 1,
    backgroundColor: theme.success,
    borderRadius: 10,
    paddingVertical: 12,
    paddingHorizontal: 15,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  mostrarTreinoButtonText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '600',
  },
  diasSemanaContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 5,
  },
  diaButton: {
    backgroundColor: theme.backgroundSecondary,
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: theme.border,
  },
  diaButtonActive: {
    backgroundColor: theme.primary,
    borderColor: theme.primary,
  },
  diaButtonText: {
    fontSize: 13,
    color: theme.textSecondary,
    fontWeight: '500',
  },
  diaButtonTextActive: {
    color: '#fff',
    fontWeight: '600',
  },
  treinosAtuaisContainer: {
    backgroundColor: theme.primaryLight,
    borderRadius: 12,
    padding: 15,
    marginBottom: 20,
  },
  treinosAtuaisTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: theme.warning,
    marginBottom: 12,
  },
  treinoAtualCard: {
    backgroundColor: theme.card,
    borderRadius: 8,
    padding: 12,
    marginBottom: 8,
    borderLeftWidth: 3,
    borderLeftColor: theme.warning,
  },
  treinoAtualHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 4,
  },
  treinoAtualNome: {
    fontSize: 15,
    fontWeight: '600',
    color: theme.text,
    flex: 1,
  },
  deleteTreinoAtualButton: {
    backgroundColor: theme.primaryLight,
    padding: 6,
    borderRadius: 6,
  },
  treinoAtualExercicios: {
    fontSize: 12,
    color: theme.textSecondary,
  },
  selecaoTreinosTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: theme.text,
    marginBottom: 15,
    marginTop: 10,
  },
  emptyBiblioteca: {
    alignItems: 'center',
    padding: 40,
    backgroundColor: theme.backgroundSecondary,
    borderRadius: 12,
    marginBottom: 20,
  },
  emptyBibliotecaText: {
    fontSize: 16,
    color: theme.textSecondary,
    marginTop: 15,
    fontWeight: '600',
  },
  emptyBibliotecaSubtext: {
    fontSize: 14,
    color: theme.textTertiary,
    marginTop: 5,
  },
  treinosPadraoList: {
    gap: 10,
    marginBottom: 20,
  },
  treinoPadraoCard: {
    backgroundColor: theme.backgroundSecondary,
    borderRadius: 12,
    padding: 15,
    borderWidth: 2,
    borderColor: theme.border,
  },
  treinoPadraoCardSelected: {
    backgroundColor: theme.primaryLight,
    borderColor: theme.primary,
  },
  treinoPadraoHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 6,
  },
  treinoPadraoNome: {
    fontSize: 16,
    fontWeight: '600',
    color: theme.text,
    flex: 1,
  },
  treinoPadraoExercicios: {
    fontSize: 13,
    color: theme.textSecondary,
    marginLeft: 36,
  },
});

export default getStyles;
